export const ROUTES = {
  HOME: '/',
  ABOUT: '/about/',
  CATEGORIES: '/categories/',
  CONTACTS: '/contacts/',
  CLEARANCE_SALE: '/clearance_sale/',
  DELIVERY: '/delivery/',
  BASKET: '/basket/',
  CATALOG: '/catalog/',
  ORDER: '/order/',
  PRODUCT: '/product/',
  CHECKOUT: '/checkout/',

  VENETIAN_MIRRORS: '/venetian_mirrors/',
  FLOOR_MIRRORS: '/floor_mirrors/',
  FRAME_MIRRORS: '/frame_mirrors/',
  MIRROR_PANELS: '/mirror_panels/',
  MIRRORS_SUN: '/mirrors_sun/',
  CONSOLES: '/consoles/',
}
