export const IS_WINDOW_SCROLL = 'IS_WINDOW_SCROLL'

export const PRODUCT_INCREMENT = 'PRODUCT_INCREMENT '
export const PRODUCT_DECREMENT = 'PRODUCT_DECREMENT'
export const PRODUCT_REMOVE = 'PRODUCT_REMOVE'

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'

export const LOAD_PRODUCT_BY_ID_REQUEST = 'LOAD_PRODUCT_BY_ID_REQUEST'
export const LOAD_PRODUCT_BY_ID_SUCCESS = 'LOAD_PRODUCT_BY_ID_SUCCESS'
export const LOAD_PRODUCT_BY_ID_FAILURE = 'LOAD_PRODUCT_BY_ID_FAILURE'

export const LOAD_REVIEWS = 'LOAD_REVIEWS'
export const LOAD_USERS = 'LOAD_USERS'

export const ADD_REVIEW = 'ADD_REVIEW'

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const FILTER_PRODUCT = 'FILTER_PRODUCT'

export const REQUEST = '_REQUEST'
export const SUCCESS = '_SUCCESS'
export const FAILURE = '_FAILURE'




